package com.hdekker.database;

import java.time.LocalDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import com.hdekker.SSDynamoDBLocalDateTimeTypeConverter;

@DynamoDBTable(tableName = "memory-vault")
public class DynamoObject {

	String key;
	
	@DynamoDBHashKey
	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}
	
	String sortKey;

	@DynamoDBRangeKey
	@DynamoDBAutoGeneratedKey
	public String getSortKey() {
		return sortKey;
	}

	public void setSortKey(String sortKey) {
		this.sortKey = sortKey;
	}
	
	Integer version;
	
	@DynamoDBVersionAttribute
	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	
	LocalDateTime lastModified;
	
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = SSDynamoDBLocalDateTimeTypeConverter.class)
	public LocalDateTime getLastModified() {
			return lastModified;
		}
	public void setLastModified(LocalDateTime lastModified) {
		this.lastModified = lastModified;
	}
	
	LocalDateTime firstCreated;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = SSDynamoDBLocalDateTimeTypeConverter.class)
	public LocalDateTime getFirstCreated() {
		return firstCreated;
	}

	public void setFirstCreated(LocalDateTime firstCreated) {
		this.firstCreated = firstCreated;
	}
	
	
	
}
